version: "3.8"

services:
  fastapi-app:
    image: ghcr.io/medisensing/temp-model-srv:latest         # ✅ 모델 이름에 맞춰 변경
    container_name: model-temp                               # ✅ 고유하게: model-{모델이름}
    expose:
      - "9000"
    environment:
      - INTERNAL_SECRET=dev_secret
      - PYTHONUNBUFFERED=1
    labels:
      model: "temp"                                           # ✅ 게이트웨이에서 식별할 모델명
      com.centurylinklabs.watchtower.enable: "true"          # ✅ Watchtower가 감지하도록 유지
    networks: [models-net]
    restart: unless-stopped

networks:
  models-net:
    external: true

