version: "3.8"

services:
  fastapi-app:
    image: ghcr.io/medisensing/temp-model-srv:latest   #변경필요: 예시(resp-model-srv)
    container_name: model-template #변경 필요: model-{모델이름} 으로 구성
    ports:
      - "9000:9000"          #9000번 고정
    environment:
      - INTERNAL_SECRET=dev_secret #내부 네트워크망 식별용
      - PYTHONUNBUFFERED=1
    labels:
      model: "temp"                                  # 변경필요: 게이트웨이용 식별라벨, 모델이름으로 변경
      com.centurylinklabs.watchtower.enable: "true"  # 자동 업데이트 허용
    networks: [models-net]
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower # 변경금지
    container_name: watchtower   # 변경금지
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json  # 인증 정보 마운트, 변경금지
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=30
      - WATCHTOWER_REGISTRY_AUTH=true
      - WATCHTOWER_USERNAME=${WATCHTOWER_USERNAME}
      - WATCHTOWER_PASSWORD=${WATCHTOWER_PASSWORD}
      - LOG_LEVEL=debug
    networks: [models-net]
    restart: unless-stopped

networks:
  models-net:
